# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ydF9l6T47-uggS3UC8pE0HKmeCVfyYac
"""

pip install numpy==2.0.2 pillow==11.3.0

pip install torch torchvision --index-url https://download.pytorch.org/whl/cu118

pip install tensorflow==2.19.0 numba fastai gradio

pip install opencv-python matplotlib tqdm

!pip install torch --quiet

!pip install diffusers

!pip install transformers

!pip install accelerate

!pip install safetensors --quiet

import os
os.environ['PYTORCH_CUDA_ALLOC_CONF'] = 'max_split_size_mb:256'

# STEP 2: LOAD YOUR JSON
import json
with open('/content/scene_data.json', 'r') as f:
    data = json.load(f)

print(f" Loaded: {len(data['stories'])} stories")
for story_key, story_val in data["stories"].items():
    print(f"   {story_val['title']}: {len(story_val['scenes'])} scenes")
print("="*60)

# STEP 3: PERFECT IMAGE GENERATOR
import torch
from diffusers import StableDiffusionXLPipeline, EulerDiscreteScheduler
from PIL import Image, ImageFilter, ImageEnhance
import numpy as np
import gc

class PerfectImageGenerator:
    def __init__(self):
        print(" Loading PERFECT model for photorealism...")

        # Use SDXL with REFINER for best quality
        self.pipe = StableDiffusionXLPipeline.from_pretrained(
            "stabilityai/stable-diffusion-xl-base-1.0",
            torch_dtype=torch.float16,
            variant="fp16",
            use_safetensors=True
        ).to("cuda")

        # Better scheduler for quality
        self.pipe.scheduler = EulerDiscreteScheduler.from_config(
            self.pipe.scheduler.config,
            timestep_spacing="trailing"
        )

        # Memory optimization
        self.pipe.enable_attention_slicing()
        self.pipe.enable_vae_slicing()

        print(" Model ready for pixel-perfect generation")

        # PERFECT PROMPT TEMPLATES
        self.templates = {
            "quality": "masterpiece, best quality, 8k, ultra detailed, photorealistic, sharp focus, ",
            "wide_angle": "wide-angle lens, full scene visible, cinematic framing, ",
            "lighting": "professional lighting, natural illumination, perfect exposure, ",
            "human_real": "realistic human anatomy, perfect facial features, natural skin texture, detailed eyes, correct hand anatomy, ",
            "scene_detail": "detailed environment, realistic textures, proper depth of field, "
        }

    def create_perfect_prompt(self, json_prompt, has_humans):
        """Create pixel-perfect prompt from JSON"""
        # Start with quality templates
        perfect_prompt = (
            f"{self.templates['quality']}"
            f"{self.templates['wide_angle']}"
            f"{self.templates['lighting']}"
            f"{self.templates['scene_detail']}"
        )

        # Add human realism if needed
        if has_humans:
            perfect_prompt += self.templates['human_real']

        # Add the JSON prompt exactly
        perfect_prompt += json_prompt

        return perfect_prompt

    def generate_image(self, json_prompt, story_name, scene_num, output_path):
        """Generate ONE perfect image"""
        print(f"\n Scene {scene_num}: {json_prompt[:60]}...")

        # Check if humans are in scene
        has_humans = any(word in json_prompt.lower() for word in
                        ['boy', 'girl', 'man', 'woman', 'child', 'person', 'people'])

        # Create perfect prompt
        prompt = self.create_perfect_prompt(json_prompt, has_humans)

        # Negative prompt to block ALL bad quality
        negative = (
            "blurry, cartoon, anime, painting, drawing, sketch, 3d, render, "
            "deformed, ugly, bad anatomy, disfigured, poorly drawn face, "
            "mutated hands, poorly drawn hands, fused fingers, too many fingers, "
            "long neck, doll, plastic, mannequin, alien, monster, "
            "cloned face, extra limbs, missing limbs, "
            "oversaturated, underexposed, lowres, bad quality, worst quality"
        )

        # Consistent seed
        seed = hash(f"{story_name}_{scene_num}") % 1000000

        try:
            # Generate at 1024x768 (perfect widescreen)
            image = self.pipe(
                prompt=prompt,
                negative_prompt=negative,
                height=768,    # Height for widescreen
                width=1024,    # Width for widescreen
                num_inference_steps=35,  # More steps = better quality
                guidance_scale=7.5,      # Balanced
                generator=torch.Generator(device="cuda").manual_seed(seed)
            ).images[0]

            # Apply pixel-perfect enhancement
            image = self.enhance_pixels(image, json_prompt)

            # Save with maximum quality
            image.save(output_path, quality=100, subsampling=0)

            print(f"    Saved: {output_path}")
            return True

        except Exception as e:
            print(f"    Error: {e}")
            return False

    def enhance_pixels(self, image, prompt):
        """Enhance every pixel for realism"""
        # Convert to RGB
        if image.mode != 'RGB':
            image = image.convert('RGB')

        # 1. Sharpening for pixel clarity
        image = image.filter(ImageFilter.UnsharpMask(
            radius=1.0,
            percent=80,  # Strong sharpening
            threshold=0
        ))

        # 2. Enhance contrast for depth
        enhancer = ImageEnhance.Contrast(image)
        image = enhancer.enhance(1.15)

        # 3. Adjust brightness based on scene
        prompt_lower = prompt.lower()
        if 'sunny' in prompt_lower or 'bright' in prompt_lower:
            enhancer = ImageEnhance.Brightness(image)
            image = enhancer.enhance(1.08)
        elif 'night' in prompt_lower or 'dark' in prompt_lower:
            enhancer = ImageEnhance.Brightness(image)
            image = enhancer.enhance(0.92)

        # 4. Add subtle grain (real photos have grain)
        np_image = np.array(image, dtype=np.float32)
        noise = np.random.normal(0, 1.5, np_image.shape)
        np_image = np.clip(np_image + noise, 0, 255).astype(np.uint8)

        return Image.fromarray(np_image)

    def cleanup(self):
        del self.pipe
        torch.cuda.empty_cache()
        gc.collect()

# STEP 4: GENERATE ALL IMAGES
print(" STARTING PIXEL-PERFECT GENERATION")
print("="*60)
print("Creating 1024x768 wide-angle photorealistic images")
print("Each image will match JSON descriptions exactly")
print("="*60)

import os
import time

# Create output directory
output_dir = "/content/pixel_perfect_images"
os.makedirs(output_dir, exist_ok=True)

# Initialize generator
generator = PerfectImageGenerator()

# Generate images
success_count = 0
total_images = sum(len(s["scenes"]) for s in data["stories"].values())

for story_key, story_val in data["stories"].items():
    print(f"\n {story_val['title']}")
    print("-" * 50)

    # Create story folder
    story_dir = os.path.join(output_dir, story_key)
    os.makedirs(story_dir, exist_ok=True)

    for scene in story_val["scenes"]:
        scene_num = scene["scene_number"]
        json_prompt = scene.get("prompt", "")

        # Output path
        output_path = os.path.join(story_dir, f"scene_{scene_num}.jpg")

        # Generate
        start = time.time()
        success = generator.generate_image(
            json_prompt=json_prompt,
            story_name=story_key,
            scene_num=scene_num,
            output_path=output_path
        )

        if success:
            success_count += 1
            print(f"     {time.time()-start:.1f}s")
        else:
            print(f"    Failed")

        # Clear memory
        torch.cuda.empty_cache()
        gc.collect()
        time.sleep(1)

# Cleanup
generator.cleanup()

# STEP 8: CREATE ZIP
print("\n Creating zip...")
!cd /content && zip -r pixel_perfect_images.zip pixel_perfect_images/

print("\n ZIP FILE: pixel_perfect_images.zip")
print("\n DOWNLOAD:")
print("1. Click folder icon ")
print("2. Find 'pixel_perfect_images.zip'")
print("3. Right-click → Download")
print("\n Individual files: /content/pixel_perfect_images/")

print("\n" + "="*60)
print(" MODULE 2A COMPLETE!")
print(" Pixel-perfect images")
print(" Wide-angle (1024x768)")
print(" Real human features")
print(" Matches JSON exactly")
print("="*60)

pip freeze > requirements.txt

